### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by chikiuso** [TsinghuaAI/CPM-1-Generate#55]
請指教，我運行 bash scripts/generate_text.sh ./cpm-large 結果如下：

  File "generate_samples.py", line 233
    if args.fp16:
                ^
TabError: inconsistent use of tabs and spaces in indentation
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'generate_samples.py', '--local_rank=1', '--model-parallel-size', '2', '--num-layers', '32', '--hidden-size', '2560', '--load', './cpm-large', '--num-attention-heads', '32', '--seq-length', '1024', '--max-position-embeddings', '1024', '--fp16', '--cache-dir', 'cache', '--out-seq-length', '512', '--temperature', '0.9', '--top_k', '0', '--top_p', '0', '--tokenizer-path', 'bpe_3w_new/', '--vocab-size', '30000']' returned non-zero exit status 1.
  File "generate_samples.py", line 233
    if args.fp16:
                ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by Misaka17032** [comment]
最后一次commit时作者错误地使用了缩进。[修复版](https://github.com/Misaka17032/CPM-1-Generate)
