### ISSUE TITLE
CUDA版本和torch版本不匹配

### ISSUE THREAD

**Issue by basketballandlearn** [TsinghuaAI/CPM-1-Generate#59]
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Generate Samples
Generate Samples
WARNING: No training data specified
WARNING: No training data specified
using world size: 2 and model-parallel size: 2
 > using dynamic loss scaling
Traceback (most recent call last):
  File "generate_samples.py", line 385, in <module>
Traceback (most recent call last):
  File "generate_samples.py", line 385, in <module>
    main()
    main()
  File "generate_samples.py", line 365, in main
  File "generate_samples.py", line 365, in main
    initialize_distributed(args)
    initialize_distributed(args)
  File "generate_samples.py", line 97, in initialize_distributed
  File "generate_samples.py", line 97, in initialize_distributed
    device = args.rank % torch.cuda.device_count()
ZeroDivisionError: integer division or modulo by zero
    device = args.rank % torch.cuda.device_count()
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'generate_samples.py', '--local_rank=1', '--model-parallel-size', '2', '--num-layers', '32', '--hidden-size', '2560', '--load', 'CPM-large/80000/', '--num-attention-heads', '32', '--seq-length', '1024', '--max-position-embeddings', '1024', '--cache-dir', 'cache', '--out-seq-length', '512', '--temperature', '0.9', '--top_k', '0', '--top_p', '0', '--tokenizer-path', 'bpe_3w_new/', '--vocab-size', '30000', '--input-text', 'example.txt']' returned non-zero exit status 1.

docker镜像的torch版本是1.2的，我的cuda是10.0的，我使用torch.cuda.is_available()返回0，所以猜测是版本不兼容，请问如何解决呢...（很想跑起来试试）

**Comment by zzy14** [comment]
按道理来说docker里是有自己的cuda环境的，您在docker里`nvidia-smi`可以看见可用显卡吗？
