### ISSUE TITLE
运行时报错： The size of tensor a (36) must match the size of tensor b (18) at non-singleton dimension 3

### ISSUE THREAD

**Issue by acst1223** [TsinghuaAI/CPM-1-Generate#60]
试图跑bash scripts/generate_text.sh CPM-large/ example.txt 的时候出现问题： The size of tensor a (36) must match the size of tensor b (18) at non-singleton dimension 3

完整输出如下：
```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Generate Samples
Generate Samples
WARNING: No training data specified
WARNING: No training data specified
using world size: 2 and model-parallel size: 2 
 > using dynamic loss scaling
> initializing model parallel with size 2
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
building CPM model ...
 > number of parameters on model parallel rank 1: 1300096000
 > number of parameters on model parallel rank 0: 1300096000
global rank 0 is loading checkpoint CPM-large/80000/mp_rank_00_model_states.pt
global rank 1 is loading checkpoint CPM-large/80000/mp_rank_01_model_states.pt
  successfully loaded CPM-large/80000/mp_rank_01_model_states.pt
  successfully loaded CPM-large/80000/mp_rank_00_model_states.pt
Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
DEBUG:jieba:Loading model from cache /tmp/jieba.cache
Loading model from cache /tmp/jieba.cache
DEBUG:jieba:Loading model from cache /tmp/jieba.cache
Loading model cost 0.547 seconds.
DEBUG:jieba:Loading model cost 0.547 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.
Loading model cost 0.602 seconds.
DEBUG:jieba:Loading model cost 0.602 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.
Traceback (most recent call last):
  File "generate_samples.py", line 384, in <module>
    main()
  File "generate_samples.py", line 380, in main
    generate_samples(model, tokenizer, args, torch.cuda.current_device())
  File "generate_samples.py", line 228, in generate_samples
    logits, past_key_values = model(tokens[:, :context_length], position_ids[:, :context_length], attention_mask[:, :, :context_length, :context_length], past_key_values=past_key_values, use_cache=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tiger/arnold_experiment/model/distributed.py", line 78, in forward
    return self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tiger/arnold_experiment/fp16/fp16.py", line 65, in forward
    return fp16_to_fp32(self.module(*(fp32_to_fp16(inputs)), **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tiger/arnold_experiment/model/gpt2_modeling.py", line 94, in forward
    transformer_output, presents = self.transformer(embeddings, attention_mask, past_key_values=past_key_values, use_cache=use_cache)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
Traceback (most recent call last):
  File "generate_samples.py", line 384, in <module>
    result = self.forward(*input, **kwargs)
  File "/opt/tiger/arnold_experiment/mpu/transformer.py", line 447, in forward
    hidden_states, present = layer(hidden_states, attention_mask, layer_past=layer_past, use_cache=use_cache)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    main()
  File "generate_samples.py", line 380, in main
    generate_samples(model, tokenizer, args, torch.cuda.current_device())
    result = self.forward(*input, **kwargs)  File "generate_samples.py", line 228, in generate_samples

  File "/opt/tiger/arnold_experiment/mpu/transformer.py", line 306, in forward
    attention_output, present = self.attention(layernorm_output, ltor_mask, layer_past=layer_past, use_cache=use_cache)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    logits, past_key_values = model(tokens[:, :context_length], position_ids[:, :context_length], attention_mask[:, :, :context_length, :context_length], past_key_values=past_key_values, use_cache=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tiger/arnold_experiment/mpu/transformer.py", line 148, in forward
    result = self.forward(*input, **kwargs)
  File "/opt/tiger/arnold_experiment/model/distributed.py", line 78, in forward
    attention_scores = torch.mul(attention_scores, ltor_mask) - \
RuntimeError: The size of tensor a (36) must match the size of tensor b (18) at non-singleton dimension 3
    return self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tiger/arnold_experiment/fp16/fp16.py", line 65, in forward
    return fp16_to_fp32(self.module(*(fp32_to_fp16(inputs)), **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tiger/arnold_experiment/model/gpt2_modeling.py", line 94, in forward
    transformer_output, presents = self.transformer(embeddings, attention_mask, past_key_values=past_key_values, use_cache=use_cache)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tiger/arnold_experiment/mpu/transformer.py", line 447, in forward
    hidden_states, present = layer(hidden_states, attention_mask, layer_past=layer_past, use_cache=use_cache)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tiger/arnold_experiment/mpu/transformer.py", line 306, in forward
    attention_output, present = self.attention(layernorm_output, ltor_mask, layer_past=layer_past, use_cache=use_cache)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tiger/arnold_experiment/mpu/transformer.py", line 148, in forward
    attention_scores = torch.mul(attention_scores, ltor_mask) - \
RuntimeError: The size of tensor a (36) must match the size of tensor b (18) at non-singleton dimension 3
Killing subprocess 2537
Killing subprocess 2538
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'generate_samples.py', '--local_rank=1', '--model-parallel-size', '2', '--num-layers', '32', '--hidden-size', '2560', '--load', 'CPM-large/', '--num-attention-heads', '32', '--seq-length', '1024', '--max-position-embeddings', '1024', '--fp16', '--cache-dir', 'cache', '--out-seq-length', '512', '--temperature', '0.9', '--top_k', '0', '--top_p', '0', '--tokenizer-path', 'bpe_3w_new/', '--vocab-size', '30000', '--input-text', 'example.txt']' returned non-zero exit status 1.
```

环境配置除了pytorch因为cuda的兼容问题不得不使用1.8.1之外，其余完全相同。请问可能是什么原因？谢谢！

**Comment by acst1223** [comment]
OK我发现问题在于我没有把generate_samples.py的缩进调整正确，调整好之后就没问题了

**Comment by zzy14** [comment]
> OK我发现问题在于我没有把generate_samples.py的缩进调整正确，调整好之后就没问题了

请问具体是什么的缩进，有人遇到了同样的问题，想请教一下。

**Comment by acst1223** [comment]
我已经提了一个merge request，可以解决这个问题

**Comment by zzy14** [comment]
感谢！我发现我修复fp16兼容性的问题的时候引入了缩进的问题。
